### ISSUE TITLE
可以互相学习一下，膜拜

### ISSUE THREAD

**Issue by yeshenyong** [Doragd/Algorithm-Practice-in-Industry#25]
https://github.com/yeshenyong/Wiki_Wiki/tree/master/%E6%90%9C%E7%B4%A2%E4%B8%8E%E6%8E%A8%E8%8D%90

**Comment by Doragd** [comment]
谢谢，互相学习

**Comment by yeshenyong** [comment]
您好，我是叶燊泳，已收到你的邮件。
